apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: postgres-parcial
    type: postgres
    access: proxy
    url: database:5432
    user: joomla_user
    secureJsonData:
      password: secreto_postgres
    jsonData:
      database: joomla_db
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true