server {
    listen 80;

    # 1. Enruta hacia Joomla (Portal principal)
    location / {
        proxy_pass http://joomla:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Enruta hacia Grafana
    location /grafana/ {
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
    }

    # 3. Enruta hacia Jupyter (Con WebSockets exigidos en el PDF)
    location /jupyter/ {
        proxy_pass http://jupyter:8888/;
        
        # --- Configuración obligatoria para el Kernel ---
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}